apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-helm.fullname" . }}
  labels:
    {{- include "base-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .servicePort }}
    targetPort: {{ .containerPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "base-helm.selectorLabels" . | nindent 4 }}
